---

default:
  image: docker.io/adoptopenjdk/openjdk11:alpine

variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build_app
  - build_image

build_app_job:
  stage: build_app
  script:
    - ./gradlew ::backend::build
  artifacts:
    name: bootJar
    paths:
      - ./backend/build/libs/backend-*.jar

build_image_job:
  needs:
    - build_image
  image: docker:stable
  services:
    - docker:stable-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest --file ./docker
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest


