---

default:
  image: docker.io/adoptopenjdk/openjdk11:alpine

variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - containerize
  - publish

build_job:
  stage: build
  script:
    - ./gradlew ::backend::build
  artifacts:
    name: bootJar
    paths:
      - ./backend/build/libs/backend-*.jar
